In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from openpyxl import load_workbook

In [2]:
df = pd.read_csv("orders (1).csv")
df

              Time  Type  Instrument Product       Qty.  Avg. price     Status
0   18/12/21 10:23  SELL         SBI     CNC  1000/1000      525.25   COMPLETE
1   16/12/21 15:08   BUY    ASHOKLEY     MIS  1000/1000      125.70   COMPLETE
2   16/12/21 15:08   BUY         SBI     CNC  1000/1000      520.80   COMPLETE
3   16/12/21 14:13   BUY  TATAMOTORS     MIS    250/250      490.55   COMPLETE
4   16/12/21 13:54   BUY    ASHOKLEY     MIS     0/1000      127.10  CANCELLED
5   16/12/21 13:21  SELL  TATAMOTORS     MIS    250/250      492.10   COMPLETE
6   16/12/21 12:51   BUY  TATAMOTORS     MIS      0/250      490.80  CANCELLED
7   16/12/21 12:39  SELL    ASHOKLEY     MIS  1000/1000      125.96   COMPLETE
8   16/12/21 12:29   BUY    ASHOKLEY     MIS  2000/2000      125.70   COMPLETE
9   16/12/21 11:22  SELL    ASHOKLEY     MIS  2000/2000      125.95   COMPLETE
10  16/12/21 10:47  SELL    ASHOKLEY     MIS     0/2000      124.45  CANCELLED
11  16/12/21 10:46  SELL    ASHOKLEY     MIS  2000/2000      125.95   COMPLETE
12  16/12/21 10:24   BUY    ASHOKLEY     MIS  1000/1000      125.60   COMPLETE
13  16/12/21 10:23   BUY    ASHOKLEY     MIS  1000/1000      125.65   COMPLETE

In [3]:
df.describe()

       Avg. price
count   14.000000
mean   260.825714
std    188.268428
min    124.450000
25%    125.700000
50%    125.955000
75%    490.737500
max    525.250000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Time        14 non-null     object
 1   Type        14 non-null     object
 2   Instrument  14 non-null     object
 3   Product     14 non-null     object
 4   Qty.        14 non-null     object
 5   Avg. price  14 non-null     float64
 6   Status      14 non-null     object
dtypes: float64(1), object(6)
memory usage: 916.0+ bytes

In [5]:
df.head()

             Time  Type  Instrument Product       Qty.  Avg. price     Status
0  18/12/21 10:23  SELL         SBI     CNC  1000/1000      525.25   COMPLETE
1  16/12/21 15:08   BUY    ASHOKLEY     MIS  1000/1000      125.70   COMPLETE
2  16/12/21 15:08   BUY         SBI     CNC  1000/1000      520.80   COMPLETE
3  16/12/21 14:13   BUY  TATAMOTORS     MIS    250/250      490.55   COMPLETE
4  16/12/21 13:54   BUY    ASHOKLEY     MIS     0/1000      127.10  CANCELLED

In [6]:
# Only Show MIS and Complete data

f_df = df[(df["Product"] == "MIS") & (df["Status"] == "COMPLETE")].copy()
f_df

              Time  Type  Instrument Product       Qty.  Avg. price    Status
1   16/12/21 15:08   BUY    ASHOKLEY     MIS  1000/1000      125.70  COMPLETE
3   16/12/21 14:13   BUY  TATAMOTORS     MIS    250/250      490.55  COMPLETE
5   16/12/21 13:21  SELL  TATAMOTORS     MIS    250/250      492.10  COMPLETE
7   16/12/21 12:39  SELL    ASHOKLEY     MIS  1000/1000      125.96  COMPLETE
8   16/12/21 12:29   BUY    ASHOKLEY     MIS  2000/2000      125.70  COMPLETE
9   16/12/21 11:22  SELL    ASHOKLEY     MIS  2000/2000      125.95  COMPLETE
11  16/12/21 10:46  SELL    ASHOKLEY     MIS  2000/2000      125.95  COMPLETE
12  16/12/21 10:24   BUY    ASHOKLEY     MIS  1000/1000      125.60  COMPLETE
13  16/12/21 10:23   BUY    ASHOKLEY     MIS  1000/1000      125.65  COMPLETE

In [7]:
f_df[["Executed_Qty", "Ordered_Qty"]] = f_df["Qty."].str.split("/", expand=True).astype(int)
f_df[["Executed_Qty", "Ordered_Qty"]]

    Executed_Qty  Ordered_Qty
1           1000         1000
3            250          250
5            250          250
7           1000         1000
8           2000         2000
9           2000         2000
11          2000         2000
12          1000         1000
13          1000         1000

In [8]:
f_df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Executed_Qty,Ordered_Qty
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000/1000,125.70,COMPLETE,1000,1000
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250/250,490.55,COMPLETE,250,250
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250/250,492.10,COMPLETE,250,250
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000/1000,125.96,COMPLETE,1000,1000
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000/2000,125.70,COMPLETE,2000,2000
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000/1000,125.60,COMPLETE,1000,1000
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000/1000,125.65,COMPLETE,1000,1000

In [9]:
# Brokerage 

f_df["Trade_Value"] = f_df["Executed_Qty"] * f_df["Avg. price"]
f_df["Brokerage"] = (f_df["Trade_Value"] * 0.0003).clip(upper=20)
f_df["Brokerage"]

1     20.0
3     20.0
5     20.0
7     20.0
8     20.0
9     20.0
11    20.0
12    20.0
13    20.0
Name: Brokerage, dtype: float64

In [10]:
f_df = f_df.loc[:,~f_df.columns.duplicated()].copy()
f_df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Executed_Qty,Ordered_Qty,Trade_Value,Brokerage
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000/1000,125.70,COMPLETE,1000,1000,125700.0,20.0
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250/250,490.55,COMPLETE,250,250,122637.5,20.0
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250/250,492.10,COMPLETE,250,250,123025.0,20.0
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000/1000,125.96,COMPLETE,1000,1000,125960.0,20.0
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000/2000,125.70,COMPLETE,2000,2000,251400.0,20.0
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000/1000,125.60,COMPLETE,1000,1000,125600.0,20.0
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000/1000,125.65,COMPLETE,1000,1000,125650.0,20.0

In [11]:
f_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 1 to 13
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Time          9 non-null      object
 1   Type          9 non-null      object
 2   Instrument    9 non-null      object
 3   Product       9 non-null      object
 4   Qty.          9 non-null      object
 5   Avg. price    9 non-null      float64
 6   Status        9 non-null      object
 7   Executed_Qty  9 non-null      int64
 8   Ordered_Qty   9 non-null      int64
 9   Trade_Value   9 non-null      float64
 10  Brokerage     9 non-null      float64
dtypes: float64(3), int64(2), object(6)
memory usage: 864.0+ bytes

In [12]:
#  Column ke rename karna hai 

f_df = f_df.rename(columns={
    'trade_value': 'Trade_Value'
    
})
f_df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Executed_Qty,Ordered_Qty,Trade_Value,Brokerage
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000/1000,125.70,COMPLETE,1000,1000,125700.0,20.0
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250/250,490.55,COMPLETE,250,250,122637.5,20.0
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250/250,492.10,COMPLETE,250,250,123025.0,20.0
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000/1000,125.96,COMPLETE,1000,1000,125960.0,20.0
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000/2000,125.70,COMPLETE,2000,2000,251400.0,20.0
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000/1000,125.60,COMPLETE,1000,1000,125600.0,20.0
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000/1000,125.65,COMPLETE,1000,1000,125650.0,20.0

In [13]:
f_df["stt"] = np.where(
    f_df["Type"] == "SELL",
    f_df["Trade_Value"] * 0.00025,
    0
).round(2)

f_df["stt"]

1      0.00
3      0.00
5     30.76
7     31.49
8      0.00
9     62.98
11    62.98
12     0.00
13     0.00
Name: stt, dtype: float64

In [14]:
f_df = f_df.rename(columns={
    'stt': 'STT'
    
})

In [15]:
f_df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Executed_Qty,Ordered_Qty,Trade_Value,Brokerage,STT
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000/1000,125.70,COMPLETE,1000,1000,125700.0,20.0,0.00
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250/250,490.55,COMPLETE,250,250,122637.5,20.0,0.00
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250/250,492.10,COMPLETE,250,250,123025.0,20.0,30.76
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000/1000,125.96,COMPLETE,1000,1000,125960.0,20.0,31.49
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000/2000,125.70,COMPLETE,2000,2000,251400.0,20.0,0.00
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0,62.98
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0,62.98
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000/1000,125.60,COMPLETE,1000,1000,125600.0,20.0,0.00
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000/1000,125.65,COMPLETE,1000,1000,125650.0,20.0,0.00

In [16]:
f_df["Transaction_Charges"] = (f_df["Trade_Value"] * 0.0000307).round(2)
f_df["Transaction_Charges"]

1     3.86
3     3.76
5     3.78
7     3.87
8     7.72
9     7.73
11    7.73
12    3.86
13    3.86
Name: Transaction_Charges, dtype: float64

In [17]:
f_df["SEBI"] = ((f_df["Trade_Value"] / 10000000) * 10).round(3)
f_df["SEBI"]

1     0.126
3     0.123
5     0.123
7     0.126
8     0.251
9     0.252
11    0.252
12    0.126
13    0.126
Name: SEBI, dtype: float64

In [18]:
f_df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Executed_Qty,Ordered_Qty,Trade_Value,Brokerage,STT,Transaction_Charges,SEBI
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000/1000,125.70,COMPLETE,1000,1000,125700.0,20.0,0.00,3.86,0.126
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250/250,490.55,COMPLETE,250,250,122637.5,20.0,0.00,3.76,0.123
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250/250,492.10,COMPLETE,250,250,123025.0,20.0,30.76,3.78,0.123
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000/1000,125.96,COMPLETE,1000,1000,125960.0,20.0,31.49,3.87,0.126
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000/2000,125.70,COMPLETE,2000,2000,251400.0,20.0,0.00,7.72,0.251
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0,62.98,7.73,0.252
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0,62.98,7.73,0.252
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000/1000,125.60,COMPLETE,1000,1000,125600.0,20.0,0.00,3.86,0.126
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000/1000,125.65,COMPLETE,1000,1000,125650.0,20.0,0.00,3.86,0.126

In [19]:
f_df["Stamp_Charges"] = np.where(f_df["Type"] == "BUY", 
                                f_df["Trade_Value"] * 0.00003,
                                0).round(2)
f_df["Stamp_Charges"]

1     3.77
3     3.68
5     0.00
7     0.00
8     7.54
9     0.00
11    0.00
12    3.77
13    3.77
Name: Stamp_Charges, dtype: float64

In [20]:
f_df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Executed_Qty,Ordered_Qty,Trade_Value,Brokerage,STT,Transaction_Charges,SEBI,Stamp_Charges
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000/1000,125.70,COMPLETE,1000,1000,125700.0,20.0,0.00,3.86,0.126,3.77
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250/250,490.55,COMPLETE,250,250,122637.5,20.0,0.00,3.76,0.123,3.68
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250/250,492.10,COMPLETE,250,250,123025.0,20.0,30.76,3.78,0.123,0.00
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000/1000,125.96,COMPLETE,1000,1000,125960.0,20.0,31.49,3.87,0.126,0.00
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000/2000,125.70,COMPLETE,2000,2000,251400.0,20.0,0.00,7.72,0.251,7.54
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0,62.98,7.73,0.252,0.00
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0,62.98,7.73,0.252,0.00
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000/1000,125.60,COMPLETE,1000,1000,125600.0,20.0,0.00,3.86,0.126,3.77
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000/1000,125.65,COMPLETE,1000,1000,125650.0,20.0,0.00,3.86,0.126,3.77

In [21]:
f_df["GST"] = (
    (f_df["Brokerage"] + f_df["SEBI"] + f_df["Transaction_Charges"] * 0.18)
)
f_df["GST"]

1     20.8208
3     20.7998
5     20.8034
7     20.8226
8     21.6406
9     21.6434
11    21.6434
12    20.8208
13    20.8208
Name: GST, dtype: float64

In [22]:
f_df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Executed_Qty,Ordered_Qty,Trade_Value,Brokerage,STT,Transaction_Charges,SEBI,Stamp_Charges,GST
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000/1000,125.70,COMPLETE,1000,1000,125700.0,20.0,0.00,3.86,0.126,3.77,20.8208
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250/250,490.55,COMPLETE,250,250,122637.5,20.0,0.00,3.76,0.123,3.68,20.7998
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250/250,492.10,COMPLETE,250,250,123025.0,20.0,30.76,3.78,0.123,0.00,20.8034
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000/1000,125.96,COMPLETE,1000,1000,125960.0,20.0,31.49,3.87,0.126,0.00,20.8226
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000/2000,125.70,COMPLETE,2000,2000,251400.0,20.0,0.00,7.72,0.251,7.54,21.6406
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0,62.98,7.73,0.252,0.00,21.6434
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0,62.98,7.73,0.252,0.00,21.6434
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000/1000,125.60,COMPLETE,1000,1000,125600.0,20.0,0.00,3.86,0.126,3.77,20.8208
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000/1000,125.65,COMPLETE,1000,1000,125650.0,20.0,0.00,3.86,0.126,3.77,20.8208

In [23]:
f_df["Total_Charges"] = f_df["Brokerage"] + f_df["SEBI"] + f_df["Transaction_Charges"] + f_df["STT"] + f_df["Stamp_Charges"] + f_df["GST"]
f_df["Total_Charges"]

1      48.5768
3      48.3628
5      75.4664
7      76.3086
8      57.1516
9     112.6054
11    112.6054
12     48.5768
13     48.5768
Name: Total_Charges, dtype: float64

In [24]:
f_df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Executed_Qty,Ordered_Qty,Trade_Value,Brokerage,STT,Transaction_Charges,SEBI,Stamp_Charges,GST,Total_Charges
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000/1000,125.70,COMPLETE,1000,1000,125700.0,20.0,0.00,3.86,0.126,3.77,20.8208,48.5768
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250/250,490.55,COMPLETE,250,250,122637.5,20.0,0.00,3.76,0.123,3.68,20.7998,48.3628
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250/250,492.10,COMPLETE,250,250,123025.0,20.0,30.76,3.78,0.123,0.00,20.8034,75.4664
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000/1000,125.96,COMPLETE,1000,1000,125960.0,20.0,31.49,3.87,0.126,0.00,20.8226,76.3086
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000/2000,125.70,COMPLETE,2000,2000,251400.0,20.0,0.00,7.72,0.251,7.54,21.6406,57.1516
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0,62.98,7.73,0.252,0.00,21.6434,112.6054
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE,2000,2000,251900.0,20.0,62.98,7.73,0.252,0.00,21.6434,112.6054
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000/1000,125.60,COMPLETE,1000,1000,125600.0,20.0,0.00,3.86,0.126,3.77,20.8208,48.5768
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000/1000,125.65,COMPLETE,1000,1000,125650.0,20.0,0.00,3.86,0.126,3.77,20.8208,48.5768

In [25]:
# 2) Stock wise and Type wise analysis with weighted Avg. price & calculated charges

In [32]:
analysis = f_df.groupby(["Instrument", "Type"]).agg(
    Qty=("Executed_Qty", "sum"),
    Turnover=("Trade_Value", "sum"),
    Brokerage=("Brokerage", "sum"),
    STT_CTT=("STT", "sum"),
    ETC=("Transaction_Charges", "sum"),
    SEBI=("SEBI", "sum"),
    GST=("GST", "sum"),
    Stamp_Charges=("Stamp_Charges", "sum"),
    Total_Charges=("Total_Charges", "sum")
).reset_index()

analysis

,Instrument,Type,Qty,Turnover,Brokerage,STT_CTT,ETC,SEBI,GST,Stamp_Charges,Total_Charges
0,ASHOKLEY,BUY,5000,628350.0,80.0,0.00,19.30,0.629,84.1030,18.85,202.8820
1,ASHOKLEY,SELL,5000,629760.0,60.0,157.45,19.33,0.630,64.1094,0.00,301.5194
2,TATAMOTORS,BUY,250,122637.5,20.0,0.00,3.76,0.123,20.7998,3.68,48.3628
3,TATAMOTORS,SELL,250,123025.0,20.0,30.76,3.78,0.123,20.8034,0.00,75.4664

In [27]:
Summary = f_df.groupby(["Instrument", "Type"]).agg(
    Turnover=("Trade_Value", "sum"),
    Total_Charges=("Total_Charges", "sum")
).reset_index()

Summary

   Instrument  Type  Turnover  Total_Charges
0    ASHOKLEY   BUY  628350.0       202.8820
1    ASHOKLEY  SELL  629760.0       301.5194
2  TATAMOTORS   BUY  122637.5        48.3628
3  TATAMOTORS  SELL  123025.0        75.4664

In [33]:
with pd.ExcelWriter("Kite_analysis_report.xlsx", engine="openpyxl") as writer:
    f_df.to_excel(writer, sheet_name="Raw_Data", index=False)
    analysis.to_excel(writer, sheet_name="Stock_Type_Analysis", index=False)
    Summary.to_excel(writer, sheet_name="Overall_Summary", index=False)

print("Excel file saved successfully!")

Excel file saved successfully!

In [34]:
summary = f_df.groupby(["Instrument", "Type"]).agg(
    Turnover=("Trade_Value", "sum"),
    Total_Charges=("Total_Charges", "sum")
).reset_index()

pivot = summary.pivot(
    index="Instrument",
    columns="Type",
    values="Turnover"
).fillna(0)

overall = f_df.groupby("Instrument")["Total_Charges"].sum().reset_index()

overall["Gross_PnL"] = (
    pivot.get("SELL", 0) - pivot.get("BUY", 0)
).values

overall["Net_PnL"] = overall["Gross_PnL"] - overall["Total_Charges"]

overall["%_Charges"] = (
    (overall["Total_Charges"] / overall["Gross_PnL"]) * 100
).round(2)

overall = overall[
    ["Instrument", "Gross_PnL", "Total_Charges", "Net_PnL", "%_Charges"]
]


total_row = pd.DataFrame({
    "Instrument": ["Total"],
    "Gross_PnL": [overall["Gross_PnL"].sum()],
    "Total_Charges": [overall["Total_Charges"].sum()],
    "Net_PnL": [overall["Net_PnL"].sum()],
    "%_Charges": [round((overall["Total_Charges"].sum() / overall["Gross_PnL"].sum()) * 100, 2)]
})

overall = pd.concat([overall, total_row], ignore_index=True)

overall

   Instrument  Gross_PnL  Total_Charges    Net_PnL  %_Charges
0    ASHOKLEY     1410.0       504.4014   905.5986      35.77
1  TATAMOTORS      387.5       123.8292   263.6708      31.96
2       Total     1797.5       628.2306  1169.2694      34.95

In [35]:
with pd.ExcelWriter("Kite_analysis_report2.xlsx", engine="openpyxl") as writer:
    f_df.to_excel(writer, sheet_name="Raw_Data", index=False)
    analysis.to_excel(writer, sheet_name="Stock_Type_Analysis", index=False)
    overall.to_excel(writer, sheet_name="Overall_Summary", index=False)

print("Excel file saved successfully!")

Excel file saved successfully!

In [36]:
# Sheet name Change
wb = load_workbook("Kite_analysis_report2.xlsx")
wb["Raw_Data"].title = "Individual Transaction"

wb.save("Kite_analysis_report2.xlsx")